# Generated by Django 6.0.1 on 2026-01-07 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=200)),
                ('time', models.TimeField()),
                ('tickets_url', models.URLField(max_length=500)),
                ('instagram_post_url', models.URLField(max_length=500)),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
    ]
