# Generated by Django 6.0.1 on 2026-01-13 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_api_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apitoken',
            options={'ordering': ['-created_at'], 'verbose_name': 'Api Token', 'verbose_name_plural': 'Api Tokens'},
        ),
    ]
